import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ColorField from "../components/ColorField";
import Form from "../components/Form";

export default function Home() {
  const [colorPattern, setColorPattern] = useState("");
  const formData = {
    mode: "",
    color: "",
  };

  function handleOnChange() {
    console.log(e.target);
    setColorPattern();
  }

  return (
    <>
      <div>
        <Head>
          <title>Color Scheme Generator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <main>
        <div className=" mx-auto w-full max-w-5xl h-full flex flex-col justify-between items-center">
          <Form onChance={handleOnChange} />
          <ColorField />
        </div>
      </main>
    </>
  );
}
