import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ColorField from "../components/ColorField";
import Form from "../components/Form";

export default function Home() {
  const [colorPattern, setColorPattern] = useState("");
  const formData = {
    mode: "",
    color: "#000000",
  };

  console.log(colorPattern);

  function handleOnChange(e) {
    const { name, value } = e.target;
    // return console.log(e.target);
    setColorPattern((oldPattern) => {
      return {
        ...oldPattern,
        [name]: value,
      };
    });
  }

  return (
    <>
      <div>
        <Head>
          <title>Color Scheme Generator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <main>
        <div className=" mx-auto w-full max-w-5xl h-full flex flex-col justify-between items-center">
          <Form
            onChange={handleOnChange}
            mode={colorPattern.mode}
            color={colorPattern.color}
          />
          <ColorField />
        </div>
      </main>
    </>
  );
}
