import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import ColorField from "../components/ColorField";
import Form from "../components/Form";

export default function Home() {
  const [colorPattern, setColorPattern] = useState({
    mode: "monochrome",
    color: "000000",
  });
  const [requestedColorPattern, setRequestedColorPattern] = useState([
    {
      color: "#000000",
    },
    {
      color: "#000000",
    },
    {
      color: "#000000",
    },
    {
      color: "#000000",
    },
    {
      color: "#000000",
    },
  ]);

  function handleOnChange(e) {
    const { name, value } = e.target;
    // return console.log(e.target);
    setColorPattern((oldPattern) => {
      return {
        ...oldPattern,
        [name]: value,
      };
    });
  }

  function getColorScheme(e) {
    e.preventDefault();
    fetch(
      `https://www.thecolorapi.com/scheme?hex=${colorPattern.color.substring(
        1
      )}&mode=${colorPattern.mode}&count=5`
    )
      .then((res) => res.json())
      .then((data) => {
        setRequestedColorPattern((oldItem) => {
          return data.colors.map((item) => {
            return { color: item.hex.value };
          });
        });
      });
  }

  return (
    <>
      <div>
        <Head>
          <title>Color Scheme Generator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <main>
        <div className=" mx-auto w-full max-w-5xl h-full flex flex-col justify-between items-center">
          <Form
            onSubmit={getColorScheme}
            onChange={handleOnChange}
            mode={colorPattern.mode}
            color={colorPattern.color}
          />
          <ColorField setColor={requestedColorPattern} />
        </div>
      </main>
    </>
  );
}
